import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
const sample=JSON.parse(await readFile(new URL('../content/samples/sample-02.json',import.meta.url),'utf8'));
const build=new URL('../scripts/build.mjs',import.meta.url).pathname;
async function run(content,{preview=false,now='2026-10-08T10:00:00Z'}={}){
 const dir=await mkdtemp(join(tmpdir(),'football-build-')),input=join(dir,'in'),out=join(dir,'out');await mkdir(input);
 try{for(let i=0;i<content.length;i++)await writeFile(join(input,`${i}.json`),JSON.stringify(content[i]));const result=spawnSync(process.execPath,[build,`--content=${input}`,`--out=${out}`,`--now=${now}`,...(preview?['--preview']:[])],{encoding:'utf8'});const html=result.status===0?await readFile(join(out,'index.html'),'utf8'):'';return {...result,html};}finally{await rm(dir,{recursive:true,force:true});}
}
function daily(date='2026-10-08',publishAt='2026-10-08T07:00:00+02:00') {return {...structuredClone(sample),id:`daily-${date}`,kind:'daily',date,publishAt,eventWindow:{start:'2026-10-07',end:date}};}
function data(html){return JSON.parse(html.match(/<script id="training-data" type="application\/json">([\s\S]*?)<\/script>/)[1]);}
test('new preview has exactly 30 questions, embedded visual material and current season',async()=>{const r=await run([],{preview:true});assert.equal(r.status,0,r.stderr);const s=data(r.html).sessions;assert.deepEqual(s.map(s=>s.id),['sample-02']);assert.equal(s[0].questions.length,30);assert.equal(s[0].questions.filter(q=>q.tags.includes('season')).length,6);assert.equal(s[0].questions.filter(q=>q.tags.includes('polish')).length,8);assert.ok(s[0].questions.filter(q=>q.media).every(q=>q.media.data.startsWith('data:image/')));assert.equal(s[0].questions.filter(q=>q.career).length,5);assert.ok(!r.html.includes('<textarea'));});
test('production omits local samples and all future answers until Warsaw release instant',async()=>{for(const [date,instant] of [['2026-10-08','2026-10-08T07:00:00+02:00'],['2026-12-08','2026-12-08T07:00:00+01:00']]){const s=daily(date,instant),release=Date.parse(instant);s.eventWindow={start:date,end:date};let r=await run([s],{now:new Date(release-1).toISOString()});assert.equal(r.status,0,r.stderr);assert.deepEqual(data(r.html).sessions,[]);assert.ok(!r.html.includes('Alaksandr Hleb'));r=await run([s],{now:new Date(release).toISOString()});assert.equal(r.status,0,r.stderr);assert.deepEqual(data(r.html).sessions.map(s=>s.id),[s.id]);}});
test('incomplete sessions, duplicated facts and source omissions fail publication',async()=>{for(const mutate of [s=>s.questions.pop(),s=>s.questions[1].factKey=s.questions[0].factKey,s=>s.questions[0].sources=[]]){const s=daily();mutate(s);assert.notEqual((await run([s])).status,0);}});
test('text career riddles and shared-coach questions publish without badge timelines',async()=>{const s=daily();s.questions[18].format='career-riddle';delete s.questions[18].career;s.questions[22].format='coach-link';s.questions[22].difficulty='bardzo trudne';const r=await run([s]);assert.equal(r.status,0,r.stderr);const published=data(r.html).sessions[0];assert.equal(published.questions[18].format,'career-riddle');assert.equal(published.questions[22].format,'coach-link');assert.equal(published.questions[22].difficulty,'bardzo trudne');const unsupported=daily();unsupported.questions[18].format='unknown-format';assert.notEqual((await run([unsupported])).status,0);});
test('image paths and credits are checked even in unreleased files',async()=>{for(const mutate of [s=>s.questions[0].media.path='../README.md',s=>delete s.questions[0].media.license]){const s=daily('2026-12-08','2026-12-08T07:00:00+01:00');mutate(s);assert.notEqual((await run([s])).status,0);}});
test('club-gap answers must match the timeline and lineup must contain eleven players',async()=>{for(const mutate of [s=>s.questions[1].career.at(-1).club='Wrong club',s=>s.questions[3].lineup.rows.pop(),s=>delete s.questions[18].career]){const s=daily();mutate(s);assert.notEqual((await run([s])).status,0);}});
test('current-season facts cannot claim unplayed dates or become recent outside the window',async()=>{for(const mutate of [s=>s.questions[6].eventDate='2026-10-09',s=>s.questions[6].tags.push('recent')]){const s=daily();mutate(s);assert.notEqual((await run([s])).status,0);}});
test('30-day cooldown is enforced across sessions; 30–59 days requires an editorial reason',async()=>{const first=daily();const second=daily('2026-10-28','2026-10-28T07:00:00+01:00');second.questions.forEach((q,i)=>{q.id=`next-${i}`;q.factKey=`next-fact-${i}`;q.prompt+=' Nowa wersja.';q.subjects=[`other:${i}`];});second.questions[0].subjects=first.questions[0].subjects;let r=await run([first,second]);assert.notEqual(r.status,0);assert.match(r.stderr,/cooldown under 30/);second.date='2026-11-08';second.id='daily-2026-11-08';second.publishAt='2026-11-08T07:00:00+01:00';second.eventWindow.end=second.date;r=await run([first,second]);assert.notEqual(r.status,0);assert.match(r.stderr,/needs a reason/);second.questions[0].cooldownReason='Different verified topic, curriculum exception.';r=await run([first,second]);assert.equal(r.status,0,r.stderr);});
